export default {
  root: "/",
  basePath: import.meta.env.DEV ? "/" : import.meta.env.VITE_BASE_PATH,
  redirect: "/redirect/:ecdsa/:eddsa",
  default: {
    root: "/",
    import: "/import",
    leaderboard: "/leaderboard",
    onboarding: "/onboarding",
    upload: "/upload",
  },
  shared: {
    root: "/shared",
    chainAssets: "/shared/vault/:alias/:uid/:chainKey",
    chainAssetsRedirect: "/shared/:uid/:chainKey",
    chains: "/shared/vault/:alias/:uid/",
    chainsRedirect: "/shared/:uid",
    leaderboard: "/shared/vault/:alias/:uid/leaderboard",
    nfts: "/shared/vault/:alias/:uid/nfts",
    nftAssets: "/shared/vault/:alias/:uid/nfts/:chainKey",
    positions: "/shared/vault/:alias/:uid/positions",
  },
  vault: {
    root: "/vault",
    chains: "/vault/balances",
    chainAssets: "/vault/balances/:chainKey",
    leaderboard: "/vault/leaderboard",
    nfts: "/vault/nfts",
    nftAssets: "/vault/nfts/:chainKey",
    positions: "/vault/positions",
  },
};
