export default {
  root: "/",
  basePath: import.meta.env.DEV ? "/" : import.meta.env.VITE_BASE_PATH,
  redirect: "/redirect/:ecdsa/:eddsa",
  default: {
    root: "/",
    airdrop: "/airdrop",
    import: "/import",
    onboarding: "/onboarding",
    swap: "/swap",
    upload: "/upload",
  },
  shared: {
    root: "/shared",
    airdrop: "/shared/vault/:alias/:uid/airdrop",
    chainAssets: "/shared/vault/:alias/:uid/:chainKey",
    chainAssetsRedirect: "/shared/:uid/:chainKey",
    chains: "/shared/vault/:alias/:uid/",
    chainsRedirect: "/shared/:uid",
    nfts: "/shared/vault/:alias/:uid/nfts",
    nftAssets: "/shared/vault/:alias/:uid/nfts/:chainKey",
    positions: "/shared/vault/:alias/:uid/positions",
    swap: "/shared/vault/:alias/:uid/swap",
  },
  vault: {
    root: "/vault",
    airdrop: "/vault/airdrop",
    achievements: "/vault/achievements",
    chains: "/vault/balances",
    chainAssets: "/vault/balances/:chainKey",
    nfts: "/vault/nfts",
    nftAssets: "/vault/nfts/:chainKey",
    positions: "/vault/positions",
    swap: "/vault/swap",
  },
};
